name = "learnsupport"
type = "webpack"
account_id = "397c1d52f9be79c988a4b07983da3256"
route = "learn.support/*"
zone_id = "54559b6c16a4200ecfb2de2405f63c82"

[site]
bucket = "./public"
entry-point = "workers-site"
